"""baseline: capture current models.py schema

Revision ID: 343dd774b86a
Revises: 
Create Date: 2026-04-16 13:17:29.118533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343dd774b86a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=25), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('account_status', sa.Enum('active', 'suspended', 'deleted', name='ck_account_status', create_constraint=True), nullable=False),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('garage',
    sa.Column('garage_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('number_of_floors', sa.Integer(), nullable=False),
    sa.Column('operating_hours', sa.String(length=100), nullable=False),
    sa.Column('front_desk_phone', sa.String(length=25), nullable=True),
    sa.CheckConstraint('number_of_floors > 0', name='chk_garage_number_of_floors'),
    sa.CheckConstraint('total_capacity > 0', name='chk_garage_total_capacity'),
    sa.PrimaryKeyConstraint('garage_id')
    )
    op.create_table('login_attempt',
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ip_address')
    )
    op.create_table('pricing_rule',
    sa.Column('rate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rate_name', sa.String(length=100), nullable=False),
    sa.Column('applicable_hours', sa.String(length=100), nullable=False),
    sa.Column('pricing_model', sa.Enum('flat', 'hourly', 'special', name='ck_pricing_model', create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('program', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('rate_id'),
    sa.UniqueConstraint('rate_name')
    )
    op.create_table('staff',
    sa.Column('operator_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'attendant', name='ck_staff_role', create_constraint=True), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('operator_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('floor',
    sa.Column('floor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('garage_id', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('floor_name', sa.String(length=50), nullable=True),
    sa.Column('total_spots', sa.Integer(), nullable=False),
    sa.Column('available_spots', sa.Integer(), nullable=False),
    sa.CheckConstraint('available_spots >= 0 AND available_spots <= total_spots', name='chk_floor_available_spots'),
    sa.CheckConstraint('floor_number >= 0', name='chk_floor_number'),
    sa.CheckConstraint('total_spots > 0', name='chk_floor_total_spots'),
    sa.ForeignKeyConstraint(['garage_id'], ['garage.garage_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('floor_id'),
    sa.UniqueConstraint('garage_id', 'floor_number', name='uq_floor_per_garage')
    )
    op.create_table('gate_event',
    sa.Column('gate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('garage_id', sa.Integer(), nullable=False),
    sa.Column('gate_type', sa.Enum('entry', 'exit', name='ck_gate_type', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'out_of_order', name='ck_gate_status', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['garage_id'], ['garage.garage_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gate_id'),
    sa.UniqueConstraint('garage_id', 'gate_type', name='uq_gate_type_per_garage')
    )
    op.create_table('session_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.operator_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_token_token'), ['token'], unique=True)

    op.create_table('system_event',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.operator_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('vehicle',
    sa.Column('vehicle_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('plate_state', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.Enum('car', 'motorcycle', 'truck', name='ck_vehicle_type', create_constraint=True), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('license_plate')
    )
    op.create_table('parking_spot',
    sa.Column('spot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('spot_type', sa.Enum('standard', 'accessibility', 'staff', 'eco', name='ck_spot_type', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('available', 'occupied', 'out_of_order', name='ck_spot_status', create_constraint=True), nullable=False),
    sa.Column('location_reference', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floor.floor_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spot_id'),
    sa.UniqueConstraint('floor_id', 'location_reference', name='uq_spot_location')
    )
    op.create_table('reservation',
    sa.Column('reservation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('driver_class', sa.String(length=20), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'cancelled', 'fulfilled', 'expired', name='ck_reservation_status', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('quoted_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('end_datetime > start_datetime', name='chk_reservation_time'),
    sa.CheckConstraint('quoted_fee >= 0', name='chk_reservation_fee'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.vehicle_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_table('occupancy_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('change_type', sa.Enum('occupied', 'freed', name='ck_change_type', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['parking_spot.spot_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('ticket',
    sa.Column('ticket_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('exit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('entry_gate_id', sa.Integer(), nullable=False),
    sa.Column('exit_gate_id', sa.Integer(), nullable=True),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'closed', 'lost', 'voided', name='ck_ticket_status', create_constraint=True), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('total_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.CheckConstraint('duration IS NULL OR duration >= 0', name='chk_ticket_duration'),
    sa.CheckConstraint('exit_timestamp IS NULL OR exit_timestamp >= entry_timestamp', name='chk_ticket_exit_after_entry'),
    sa.CheckConstraint('total_fee IS NULL OR total_fee >= 0', name='chk_ticket_total_fee'),
    sa.ForeignKeyConstraint(['entry_gate_id'], ['gate_event.gate_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exit_gate_id'], ['gate_event.gate_id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spot_id'], ['parking_spot.spot_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.vehicle_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('amount_charged', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'card', 'mobile', name='ck_payment_method', create_constraint=True), nullable=False),
    sa.Column('payment_timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('payment_status', sa.Enum('paid', 'pending', 'failed', 'refunded', name='ck_payment_status', create_constraint=True), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True),
    sa.CheckConstraint('amount_charged >= 0', name='chk_payment_amount'),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('stripe_payment_intent_id'),
    sa.UniqueConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('ticket')
    op.drop_table('occupancy_log')
    op.drop_table('reservation')
    op.drop_table('parking_spot')
    op.drop_table('vehicle')
    op.drop_table('system_event')
    with op.batch_alter_table('session_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_token_token'))

    op.drop_table('session_token')
    op.drop_table('gate_event')
    op.drop_table('floor')
    op.drop_table('staff')
    op.drop_table('pricing_rule')
    op.drop_table('login_attempt')
    op.drop_table('garage')
    op.drop_table('customer')
    # ### end Alembic commands ###
